### ISSUE TITLE
Make corner radius use DIPs

### ISSUE THREAD

**Issue by vcooley** [Especializa/nativescript-ng-shadow#3]
Currently it appears that the `cornerRadius` property on android uses pixels to calculate the shadow. It would be great if it used DIPs instead so that it is easier to get pixel perfect matching of shadows when combined with an inner layout with border-radius while also supporting multiple screen resolutions and sizes.

**Comment by berardo** [comment]
Hey @vcooley,
Thanks a lot for your suggestion (and sorry for the delay). That was the main focus of version 2.0.0.
Please give it a try and let know of any issues.
Btw, not only corner radius but also the elevation itself (as well as the new `translationZ` attribute) are now portable across different screen densities.

Thanks
