### ISSUE TITLE
Does not check for Android API >= LOLLIPOP

### ISSUE THREAD

**Issue by mrnkr** [Especializa/nativescript-ng-shadow#7]
Hi!

Awesome plugin, found the directive extremely useful, so first of all, thank you!

Anyway, I did have to use *ngIf to hide a view with a shadow on phones running android with APIs lower than 21 (LOLLIPOP) since the method View.setElevation() was not added until that update. Think it would be nice if you could add that validation to the directive before it sets the elevation...

To recreate the issue just run any app using the directive on an Android phone running Android 4.4 or lower (API 21 is implemented on Android 5.0)

**Comment by berardo** [comment]
Good catch, will look into it (feel free to submit a PR tho).
Anyway, I just released a version 2. That'd be awesome if you could give it a try and let me know of any issues.
Thanks

**Comment by mrnkr** [comment]
Sorry it took me so long to get back to you!
I'll check out the new version ASAP and if it still has the same error I'll add a validation before applying the shadow to Android views and submit a PR.

**Comment by berardo** [comment]
Done on #12
