### ISSUE TITLE
Demo app doesn't work

### ISSUE THREAD

**Issue by erkanarslan** [Especializa/nativescript-ng-shadow#8]
### Which platform(s) does your issue occur on?
- iOS

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.3.1
- Cross-platform modules: 3.3.0
- Runtime(s): 3.3.0 for iOS

### Please, tell us how to recreate the issue in as much detail as possible. 
Download this repository.
Go to demo folder
Run `npm install`
Run `tns run ios`

There is a typescript error that says it cannot find nativescript-ng-shadow package in import statement.

**Comment by berardo** [comment]
Hi @erkanarslan, I'd recommend you not to go to `demo` folder but to `src` and run:
```
npm run demo.ios
npm run demo.android
```
This will `npm install` and compile typescript resources on `src` before switching to `demo`.

Cheers
